version: '2.2'
volumes:
  coverage:
services:
  python:
    build:
      context: .
      args:
        APP_NAME: my_awesome_app # change this to your app's name
    environment:
      PYHTONDONTWRITEBYTECODE: 1
    entrypoint: python
    command:
      - -c
      - "print('Use unit, lint or app instead.')"
  app:
    env_file: .env.test
    depends_on:
      - database
    build:
      context: .
    entrypoint:
      - python
      - main.py
  integration:
    build:
      context: .
    entrypoint: python
    env_file: .env.test
    command:
      - -m
      - pytest
      - --disable-pytest-warnings
      - --maxfail=1
      - -m
      - integration
      - tests/
  unit:
    volumes:
      - coverage:/tmp
    build:
      context: .
    entrypoint: coverage
    env_file: .env.test
    environment:
      COVERAGE_FILE: /tmp/.coverage
    command:
      - run
      - -m
      - pytest
      - --disable-pytest-warnings
      - --maxfail=1
      - -m
      - unit
      - tests/
  coverage:
    volumes:
      - coverage:/tmp
    build:
      context: .
    entrypoint: coverage
    env_file: .env.test
    environment:
      COVERAGE_FILE: /tmp/.coverage
    command:
      - report
